/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayRouteImport } from './routes/play'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizQuizIdRouteImport } from './routes/quiz.$quizId'
import { Route as ArenaWingsOfFireRouteImport } from './routes/arena.wings-of-fire'
import { Route as ArenaPrincessesRouteImport } from './routes/arena.princesses'

const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaWingsOfFireRoute = ArenaWingsOfFireRouteImport.update({
  id: '/arena/wings-of-fire',
  path: '/arena/wings-of-fire',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaPrincessesRoute = ArenaPrincessesRouteImport.update({
  id: '/arena/princesses',
  path: '/arena/princesses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play': typeof PlayRoute
  '/arena/princesses': typeof ArenaPrincessesRoute
  '/arena/wings-of-fire': typeof ArenaWingsOfFireRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play': typeof PlayRoute
  '/arena/princesses': typeof ArenaPrincessesRoute
  '/arena/wings-of-fire': typeof ArenaWingsOfFireRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/play': typeof PlayRoute
  '/arena/princesses': typeof ArenaPrincessesRoute
  '/arena/wings-of-fire': typeof ArenaWingsOfFireRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/play'
    | '/arena/princesses'
    | '/arena/wings-of-fire'
    | '/quiz/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/play'
    | '/arena/princesses'
    | '/arena/wings-of-fire'
    | '/quiz/$quizId'
  id:
    | '__root__'
    | '/'
    | '/play'
    | '/arena/princesses'
    | '/arena/wings-of-fire'
    | '/quiz/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayRoute: typeof PlayRoute
  ArenaPrincessesRoute: typeof ArenaPrincessesRoute
  ArenaWingsOfFireRoute: typeof ArenaWingsOfFireRoute
  QuizQuizIdRoute: typeof QuizQuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId': {
      id: '/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/wings-of-fire': {
      id: '/arena/wings-of-fire'
      path: '/arena/wings-of-fire'
      fullPath: '/arena/wings-of-fire'
      preLoaderRoute: typeof ArenaWingsOfFireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/princesses': {
      id: '/arena/princesses'
      path: '/arena/princesses'
      fullPath: '/arena/princesses'
      preLoaderRoute: typeof ArenaPrincessesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayRoute: PlayRoute,
  ArenaPrincessesRoute: ArenaPrincessesRoute,
  ArenaWingsOfFireRoute: ArenaWingsOfFireRoute,
  QuizQuizIdRoute: QuizQuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
